version: '3.2'
services:

  collection_guides:
    build: .
    environment:
      COLLECTION_GUIDES_DB_PASSWORD: 'collection_guides_db_password'
    command: "tail -f /dev/null"

  db:
    image: library/mysql:5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  solr:
    build:
      context: .
      dockerfile: Dockerfile.solr
    entrypoint: "docker-entrypoint.sh"
    command: "solr-foreground"
